### ISSUE TITLE
Followed installation instructions.... node still shows "custom integration needs to be installed in Home Assistant for this node to function correctly” error" and 

### ISSUE THREAD

**Issue by derekcfoley** [zachowj/hass-node-red#45] opened 2020-11-07 18:25 UTC
Hi, I run HASS on a Raspberry Pi 4. I'm running the latest versions of HASS & Node Red. When I drag and drop the "entity" node onto the canvas and open it, I see "custom integration needs to be installed in Home Assistant for this node to function correctly” error" in red.

I've followed your installation instructions, created the config/custom components/nodered folder, put the zip files inside it, restarted the HASS server, when I go to HASS integrations and click the orange + symbol - I still can't see "In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Node-RED"

Nothing appears when searching for it as a new integration.

![image](https://user-images.githubusercontent.com/25664126/98448865-331e5880-2127-11eb-953b-8722a3ce185c.png)

![image](https://user-images.githubusercontent.com/25664126/98448811-d884fc80-2126-11eb-8ea1-e50136b4167e.png)

![image](https://user-images.githubusercontent.com/25664126/98448834-fbafac00-2126-11eb-9426-dca110b87a19.png)

![image](https://user-images.githubusercontent.com/25664126/98448883-5517db00-2127-11eb-960f-e1d94771fd15.png)

![image](https://user-images.githubusercontent.com/25664126/98448911-75479a00-2127-11eb-994b-837eaac4daa7.png)

**Comment by jaimyborgman** [comment] 2020-11-10 10:41
Got the same issue, anyone that could provide us with an answer?

**Comment by sirdekme211** [comment] 2020-11-15 14:57
Same for me... :(

**Comment by jaimyborgman** [comment] 2020-11-15 15:19
> Got the same issue, anyone that could provide us with an answer?

for me it was due to a firewall issue after resolving that it worked perfectly fine! so double check any firewall rules if you are using that :-)

**Comment by zachowj** [comment] 2020-11-18 07:04
Does it show in the Home Assistant logs?

https://user-images.githubusercontent.com/37859597/83593154-d9c75300-a510-11ea-8242-4a60f1e375ad.png

**Comment by gcoupe** [comment] 2020-11-26 14:25
Same issue here. Not caused by a firewall issue, AFAIK., and can't see anything in HA logs. I'm stumped.

**Comment by zachowj** [comment] 2020-11-26 14:47
> Could it be a conflict with the add-on Node-Red integration provided by Frenck?

It shouldn't as the Node-RED Add-on is just a prepackaged version of Node-RED with certain palettes pre-installed.

**Comment by gcoupe** [comment] 2020-11-26 15:41
Is this the message you mean?

2020-11-26 16:36:25 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by zachowj** [comment] 2020-11-26 15:45
@gcoupe Yes, if that's showing in your log then Node-RED custom integration has been loaded by HA and should show up on the Integrations page (Configuration > Integrations > Add Integration) able to be loaded.

**Comment by gcoupe** [comment] 2020-11-26 15:52
Aha! Got it - it's a two step process. First use HACS to bring it in, then add it via the Integration page. Sorry - I'm new to HA and getting old... Thanks.

**Comment by derekngibbs** [comment] 2020-12-25 12:47
I’m having the same issue. Installed it and getting same message. Node Red Entities are not available in HA. Node Red can see my HA entities. Anything else to try?

**Comment by derekngibbs** [comment] 2020-12-25 12:50
> > Got the same issue, anyone that could provide us with an answer?
> 
> for me it was due to a firewall issue after resolving that it worked perfectly fine! so double check any firewall rules if you are using that :-)

WHat firewall rule? My Nodered can see HA entities, but new Node Red entities don’t show up in HA. Really want to be able to trigger Nodered sequences from HA UI

**Comment by vindicatorr** [comment] 2020-12-27 03:53
I'm encountering that warning (https://github.com/zachowj/hass-node-red/issues/45#issuecomment-734367330) as well, and the node red integration doesn't show in the "Add integration" list of possibilities.
Archlinux: Version         : 2020.12.0-1
```
$ sudo find /var/lib/hass/custom_components
/var/lib/hass/custom_components
/var/lib/hass/custom_components/nodered
/var/lib/hass/custom_components/nodered/__init__.py
/var/lib/hass/custom_components/nodered/binary_sensor.py
/var/lib/hass/custom_components/nodered/config_flow.py
/var/lib/hass/custom_components/nodered/const.py
/var/lib/hass/custom_components/nodered/discovery.py
/var/lib/hass/custom_components/nodered/manifest.json
/var/lib/hass/custom_components/nodered/sensor.py
/var/lib/hass/custom_components/nodered/services.yaml
/var/lib/hass/custom_components/nodered/switch.py
/var/lib/hass/custom_components/nodered/translations
/var/lib/hass/custom_components/nodered/translations/en.json
/var/lib/hass/custom_components/nodered/translations/nb.json
/var/lib/hass/custom_components/nodered/websocket.py
```
Everything is on the same system. No VM, no HASSOS, no HACS, just installed via https://github.com/zachowj/hass-node-red#installation manual method (along with setting the hass ownership/permissions).

**Comment by r1cht3r** [comment] 2020-12-27 15:53
> I'm encountering that warning ([#45 (comment)](https://github.com/zachowj/hass-node-red/issues/45#issuecomment-734367330)) as well, and the node red integration doesn't show in the "Add integration" list of possibilities.

Also unable to add this integration via the HA integration search, just doesn't show up in spite of log entry.

**Comment by yavinmaster** [comment] 2020-12-29 18:49
I'm also having the same issue.
Homeassistant and NodeRed in docker containers.
Custom addon installed and message in the log file but node-red integration not available to add.
Other homeassistant functions appear to work it is just the entity function which has the error message.

**Comment by czech12** [comment] 2020-12-29 22:21
Same issue here.  Everything is latest stable release.  HassOS installed on VM.  I installed HACS repository, installed the HACS Node-Red integration and verified the /config/custom_components/nodered directory was created and all files exist (including translations directory).

I also see the "You are using a custom integration for nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant." log in the Home Assistant Logs.

However, when I go to "Configuration > Integrations > Add Integration", Node-Red does not show up in the list.

**Comment by czech12** [comment] 2020-12-30 00:05
Well, this doesn't make any sense, but I just attempted to add it through my HA android app and low and behold the node-red integration showed up. Earlier I was trying strictly from my Brave Browser on my laptop.

Hope this helps someone else.

**Comment by zachowj** [comment] 2020-12-30 04:36
The integration list doesn't seem to be updated after a reboot. So if you have a browser window open and install the NR integration and restart HA. Then go to the add the integration, "Configuration > Integrations > Add Integration", it doesn't show up but if you just refresh your browser the integration should show up in the list.

Can someone who is still having this issue let me know if reload the browser fixes their issue?

**Comment by vindicatorr** [comment] 2020-12-30 06:24
WOW! Yeah, you are right. I had my HA tab closed, reopened it, and found the integration.

**Comment by yavinmaster** [comment] 2020-12-30 07:11
Bingo!  Yep, that's worked for me too.
Thanks.

**Comment by r1cht3r** [comment] 2020-12-30 14:04
> The integration list doesn't seem to be updated after a reboot. So if you have a browser window open and install the NR integration and restart HA. Then go to the add the integration, "Configuration > Integrations > Add Integration", it doesn't show up but if you just refresh your browser the integration should show up in the list.
> 
> Can someone who is still having this issue let me know if reloading the browser fixes their issue?

Also can confirm this resolved the issue for me, thanks!

**Comment by DavideBedin** [comment] 2020-12-30 15:47
Similar experience on HA 2020.12.2 on a VM with HassOS 5.9, copied the files per instructions 24 hours ago ... NR not appearing as option in integrations ... several restart later it showed up and webhook finally works

**Comment by zachowj** [comment] 2020-12-31 07:12
Closing this for now. If this pops up for anyone else create a new issue.

**Closed by zachowj** 2020-12-31 07:12 UTC
