### ISSUE TITLE
mobile_app_notification_action missing info

### ISSUE THREAD

**Issue by sanathdw** [zachowj/hass-node-red#24] opened 2020-05-20 10:04 UTC
## Version of the custom_component
Node red version Installed: v0.4.3.

Note sure what other information you need in terms of config etc.. Hence did not add any.

## Describe the bug
Trying to capture event data from a mobile and using the events:all node. 
The `mobile_app_notification_action` event captured via Node Red does not have all the information which is returned. 

I see the following when I use developer tools on HA 
```
{
    "event_type": "mobile_app_notification_action",
    "data": {
        "action_2_title": "Snooze 5 mins",
        "action_3_title": "Remind me at Home",
        "sticky": "true",
        "title": "Low Battery",
        "message": "Charge your phone",
        "action_1_title": "Dismiss",
        "action_1_key": "DISMISS",
        "action_2_key": "SNOOZE",
        "action_3_key": "REMIND_HOME",
        "action": "SNOOZE"
    },
    "origin": "REMOTE",
    "time_fired": "2020-05-20T06:56:47.688083+00:00",
    "context": {
        "id": "I2345",
        "parent_id": null,
        "user_id": "1234"
   }
}
```

and below is all that is seen on the events:all node which is the out put of a debug node and on the node-red add on log section 
```
20 May 20:12:26 - [info] [debug:d932decb.3b42c] 
{
  event_type: 'mobile_app_notification_action',
  entity_id: undefined,
  event: {
    action_2_title: 'Snooze 5 mins',
    action_3_title: 'Remind me at Home',
    sticky: 'true',
    title: 'Low Battery',
    message: 'Charge your phone',
    action_1_title: 'Dismiss',
    action_1_key: 'DISMISS',
    action_2_key: 'SNOOZE',
    action_3_key: 'REMIND_HOME',
    action: 'SNOOZE'
  }
}
```
as you can see it is missing a portion of the data which provides user information.

## Debug log
There is no log other information on the hassio.log file when this event is captured when i setup logging at Info level.

**Comment by zachowj** [comment] 2020-06-04 05:20
Duplicate of https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/229

**Closed by zachowj** 2020-06-04 05:20 UTC
