### ISSUE TITLE
Switch defaulting to ON on restart on 1.4.0

### ISSUE THREAD

**Issue by cromelex** [zachowj/hass-node-red#190] opened 2023-07-10 11:36 UTC
Hi,

Since the latest update, V 1.4.0, switch entities created in node red are defaulting to On when the system is restarted, even if they were previously set to off.

Not sure if this is intended behaviour or a bug, but it is the opposite of what previously happened.

To clarify, I am seeing this with switch._entities_

Thanks,

**Comment by zachowj** [comment] 2023-07-10 15:50
Duplicate of https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/973

fixed in 0.51.1

**Closed by zachowj** 2023-07-10 15:50 UTC
