### ISSUE TITLE
No Node-red companion integration in config->integration

### ISSUE THREAD

**Issue by blablazzz** [zachowj/hass-node-red#108] opened 2022-01-09 18:17 UTC
![image](https://user-images.githubusercontent.com/37573060/148694955-06b8a4f2-ab48-416f-b329-2bf2da3a2d63.png)

HACS version - 1.19.2
Node-RED Companion - 1.0.6

hass:

Version | core-2021.12.8
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Vartotojas | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.63-v8
CPU Architecture | aarch64
Timezone | Europe/Vilnius

**Comment by rlust** [comment] 2022-01-09 18:57
Same here!

**Comment by danielbrunt57** [comment] 2022-01-09 19:01
I have the same issue.  Been troubleshooting it and ended up here.  I re-installed this HACS integration but no-go. 
It disappeared after my recent updates.
HA core-2021.12.8
HACS 1.19.2
Node-RED 10.3.1

**Comment by pooyashahidi** [comment] 2022-01-09 19:56
I had the same problem. Check out your folder structure.

As the readme says it should be something like this:
```
custom_components/nodered/translations/en.json
custom_components/nodered/__init__.py
custom_components/nodered/binary_sensor.py
custom_components/nodered/config_flow.py
...
```
But for some reason it was like this:
```bash
custom_components/nodered/__init__.py #empty file
custom_components/nodered/nodered/translations/en.json
custom_components/nodered/nodered/__init__.py
custom_components/nodered/nodered/binary_sensor.py
custom_components/nodered/nodered/config_flow.py
...
```

**Comment by zachowj** [comment] 2022-01-09 20:26
Duplicate of #107

Make sure you're running the latest HACS.

**Closed by zachowj** 2022-01-09 20:26 UTC

**Comment by danielbrunt57** [comment] 2022-01-09 20:34
I re-installed NR Companion and updated HACS in same session then restarted HA but Companion was not listed in integrations.  I just checked after doing nothing and it is now.  I think HACS was still starting up when I checked before...
<img width="204" alt="image" src="https://user-images.githubusercontent.com/49846893/148699736-33f024b2-9be7-4191-a263-7ea8f17cc4b8.png">

**Comment by blablazzz** [comment] 2022-01-10 11:38
i am running the latest HACS 1.19.2

**Comment by danielbrunt57** [comment] 2022-01-10 18:25
> i am running the latest HACS 1.19.2

...and you see no Node-Red Companion integration?

**Comment by sstratoti** [comment] 2022-01-15 17:24
Having the same problem. HACS is 1.19.3. Downloading Node Red Companion and is shows in the directory of 

custom_components/nodered

In my integrations tiles, it said that nodered failed to load. Then I removed it and tried to re-add it, and it can't find it.

**Comment by sstratoti** [comment] 2022-01-15 17:30
OK, rebooted the server and did a force refresh and it now shows up. I think it was a cache issue with the integrations page.
