### ISSUE TITLE
Node-RED Companion Integration doesn't work after update to 1.0.6

### ISSUE THREAD

**Issue by MiguelCosta** [zachowj/hass-node-red#110] opened 2022-01-09 20:00 UTC
## Version of the custom_component

1.0.6

## Configuration

```yaml
Logger: homeassistant.setup
Source: setup.py:153
First occurred: 19:51:51 (1 occurrences)
Last logged: 19:51:51

Setup failed for nodered: Integration not found.
```

## Describe the bug

Integration don't load. Someone with the same problem?

![image](https://user-images.githubusercontent.com/645482/148698547-2a83a69a-46d1-4845-b258-137866d76f47.png)

![image](https://user-images.githubusercontent.com/645482/148698452-9bb1dcad-add8-42dd-8d86-7f55c4771407.png)

## Debug log

N/A

**Comment by pooyashahidi** [comment] 2022-01-09 20:07
duplicate of #108

**Comment by zachowj** [comment] 2022-01-09 20:26
Duplicate of #107

Make sure you're running the latest HACS.

**Closed by zachowj** 2022-01-09 20:26 UTC

**Comment by MiguelCosta** [comment] 2022-01-09 20:33
@zachowj I am running the last version of HACS..

**Comment by zachowj** [comment] 2022-01-09 20:36
https://github.com/zachowj/hass-node-red/issues/107#issuecomment-1008269905

Try that has see if it fixes your issue.
